replicaCount: 1
image:
  url: registry.efarda.ir/
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"
  name: nginx
  labels:
    app: nginx
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: ""
service:
  type: ClusterIP
  port: 80
