replicaCount: 1
image:
  url: nginx:latest
  pullPolicy: IfNotPresent
  name: nginx-2
  labels:
    app: nginx-2
  namespace: argocd
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: ""
service:
  type: ClusterIP
  port: 8080
