apiVersion: v1
kind: Secret
metadata:
  name: efarda-registry
  namespace: {{ .namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5lZmFyZGEuaXIiOnsidXNlcm5hbWUiOiJyZWdpc3RyeSIsInBhc3N3b3JkIjoiMlZkO2srSkQodSpaUmFyaCIsImVtYWlsIjoicmVnaXN0cnlAZWZhcmRhLmlyIiwiYXV0aCI6ImNtVm5hWE4wY25rNk1sWmtPMnNyU2tRb2RTcGFVbUZ5YUE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
